apiVersion: v1
kind: Service
metadata:
  name: cv-service
  namespace: k8s-exercises
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: cv-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cv-service
  name: cv-service-deploy
  namespace: k8s-exercises
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cv-service
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: cv-service
    spec:
      containers:
      - name: cv-service
        image: lityourcode/cv-service:0.1
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: UUID_SERVICE_NAME
          value: cv-service
        ports:
        - containerPort: 8080
          name: http
