apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: k8s-exercises-ingress
spec:
  rules:
  - host: k8s-exercises.chilling.dev
  - http:
      paths:
      - path: /
        backend:
          serviceName: cv-service
          servicePort: 8080
      - path: /cv
        backend:
          serviceName: cv-service
          servicePort: 8080

