# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem 'sinatra'
gem 'sinatra-contrib'
gem 'puma'
gem 'rack-cache'
gem 'redis-rack-cache'
gem 'activerecord'
gem 'sinatra-activerecord'
gem 'mysql2'
gem 'rake'
gem 'faker'

group :development do
  gem 'sqlite3'
end
