# Rakefile
require "sinatra/activerecord/rake"

namespace :db do
  task :load_config do
    require "./service.rb"
  end
end

namespace :user do
  task :generate_data do
    require './service.rb'
    User.delete_all if User.count > 100
    10.times do |t|
      User.create(name: Faker::Name.unique.name, introduction: Faker::Quotes::Shakespeare.hamlet_quote)
    end
  end
end
